#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Perl4-CoreLibs
Version  : 0.004
Release  : 5
URL      : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Perl4-CoreLibs-0.004.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/Z/ZE/ZEFRAM/Perl4-CoreLibs-0.004.tar.gz
Summary  : 'libraries historically supplied with Perl 4'
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan

%description
NAME
Perl4::CoreLibs - libraries historically supplied with Perl 4
DESCRIPTION
This is a collection of ".pl" files that were bundled with the Perl
core until core version 5.15.1.  Relying on their presence in the core
distribution is deprecated; they should be acquired from this CPAN
distribution instead.  From core version 5.13.3 until their removal, the
core versions of these libraries emit a deprecation warning when loaded.
The CPAN version does not emit such a warning.

%package dev
Summary: dev components for the perl-Perl4-CoreLibs package.
Group: Development
Provides: perl-Perl4-CoreLibs-devel = %{version}-%{release}

%description dev
dev components for the perl-Perl4-CoreLibs package.


%prep
%setup -q -n Perl4-CoreLibs-0.004

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1Perl4/CoreLibs.pm
/usr/lib/perl5/vendor_perl/5.28.1abbrev.pl
/usr/lib/perl5/vendor_perl/5.28.1assert.pl
/usr/lib/perl5/vendor_perl/5.28.1bigfloat.pl
/usr/lib/perl5/vendor_perl/5.28.1bigint.pl
/usr/lib/perl5/vendor_perl/5.28.1bigrat.pl
/usr/lib/perl5/vendor_perl/5.28.1cacheout.pl
/usr/lib/perl5/vendor_perl/5.28.1chat2.pl
/usr/lib/perl5/vendor_perl/5.28.1complete.pl
/usr/lib/perl5/vendor_perl/5.28.1ctime.pl
/usr/lib/perl5/vendor_perl/5.28.1dotsh.pl
/usr/lib/perl5/vendor_perl/5.28.1exceptions.pl
/usr/lib/perl5/vendor_perl/5.28.1fastcwd.pl
/usr/lib/perl5/vendor_perl/5.28.1find.pl
/usr/lib/perl5/vendor_perl/5.28.1finddepth.pl
/usr/lib/perl5/vendor_perl/5.28.1flush.pl
/usr/lib/perl5/vendor_perl/5.28.1ftp.pl
/usr/lib/perl5/vendor_perl/5.28.1getcwd.pl
/usr/lib/perl5/vendor_perl/5.28.1getopt.pl
/usr/lib/perl5/vendor_perl/5.28.1getopts.pl
/usr/lib/perl5/vendor_perl/5.28.1hostname.pl
/usr/lib/perl5/vendor_perl/5.28.1importenv.pl
/usr/lib/perl5/vendor_perl/5.28.1look.pl
/usr/lib/perl5/vendor_perl/5.28.1newgetopt.pl
/usr/lib/perl5/vendor_perl/5.28.1open2.pl
/usr/lib/perl5/vendor_perl/5.28.1open3.pl
/usr/lib/perl5/vendor_perl/5.28.1pwd.pl
/usr/lib/perl5/vendor_perl/5.28.1shellwords.pl
/usr/lib/perl5/vendor_perl/5.28.1stat.pl
/usr/lib/perl5/vendor_perl/5.28.1syslog.pl
/usr/lib/perl5/vendor_perl/5.28.1tainted.pl
/usr/lib/perl5/vendor_perl/5.28.1termcap.pl
/usr/lib/perl5/vendor_perl/5.28.1timelocal.pl
/usr/lib/perl5/vendor_perl/5.28.1validate.pl

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Perl4::CoreLibs.3
